import type { Pool } from 'pg'
import { inTransaction } from '../../../platform/transaction.js'
import { CashOnDeliveryTransitionConflictError } from '../domain/errors.js'
import type { CompletionSessionStatus } from '../domain/completion-session-state-machine.js'
import type { CashOnDeliveryPaymentStatus } from '../domain/cash-on-delivery-payment-state-machine.js'
import type { CashOnDeliveryPayment, CashOnDeliveryPaymentRepository, CreateCashOnDeliveryPayment } from '../ports/cash-on-delivery-payment-repository.js'
import type { CompletionSession, CompletionSessionRepository, CreateOrResumeCompletionSession } from '../ports/completion-session-repository.js'
import type { MerchantConnect, MerchantConnectRepository } from '../ports/merchant-connect-repository.js'
import type { MerchantTerminalLocation, MerchantTerminalLocationRepository } from '../ports/merchant-terminal-location-repository.js'

type Row = Record<string, unknown>
const session = (r: Row): CompletionSession => ({ id: String(r.id), orderId: String(r.order_id), driverId: String(r.driver_id), expectedOrderVersion: Number(r.expected_order_version), status: r.status as CompletionSessionStatus, codeVerifiedAt: r.code_verified_at as Date | null, expiresAt: r.expires_at as Date, completedAt: r.completed_at as Date | null })
const payment = (r: Row): CashOnDeliveryPayment => ({ id: String(r.id), orderId: String(r.order_id), sessionId: String(r.session_id), merchantId: String(r.merchant_id), driverId: String(r.driver_id), attemptNo: Number(r.attempt_no), stripeAccountId: String(r.stripe_account_id), amountCents: Number(r.amount_cents), currency: 'eur', stripePaymentIntentId: r.stripe_payment_intent_id as string | null, stripeChargeId: r.stripe_charge_id as string | null, status: r.status as CashOnDeliveryPaymentStatus, captureIdempotencyKey: String(r.capture_idempotency_key), createIdempotencyKey: String(r.create_idempotency_key), readerType: r.reader_type as CashOnDeliveryPayment['readerType'], readerSerial: r.reader_serial as string | null, terminalLocationId: String(r.terminal_location_id), failureCode: r.failure_code as string | null, declineCode: r.decline_code as string | null })

export class PostgresCompletionSessionRepository implements CompletionSessionRepository {
  constructor(private readonly pool: Pool) {}
  async createOrResume(input: CreateOrResumeCompletionSession): Promise<CompletionSession> {
    return inTransaction(this.pool, async client => {
      const existing = await client.query<Row>("select * from order_delivery_completion_sessions where order_id = $1 and status in ('open','code_verified','payment_pending','payment_succeeded') order by created_at desc limit 1 for update", [input.orderId])
      if (existing.rows[0] !== undefined) return session(existing.rows[0])
      try { const result = await client.query<Row>("insert into order_delivery_completion_sessions(order_id, driver_id, expected_order_version, status, expires_at) values($1,$2,$3,'open',$4) returning *", [input.orderId, input.driverId, input.expectedOrderVersion, input.expiresAt]); return session(result.rows[0]!) }
      catch (error: unknown) { if ((error as { code?: string }).code !== '23505') throw error; const retry = await client.query<Row>("select * from order_delivery_completion_sessions where order_id = $1 and status in ('open','code_verified','payment_pending','payment_succeeded') order by created_at desc limit 1 for update", [input.orderId]); if (retry.rows[0] === undefined) throw error; return session(retry.rows[0]) }
    })
  }
  async findByOrderId(orderId: string): Promise<CompletionSession | null> { const r = await this.pool.query<Row>('select * from order_delivery_completion_sessions where order_id=$1 order by created_at desc limit 1', [orderId]); return r.rows[0] === undefined ? null : session(r.rows[0]) }
  async transition(input: { id: string; from: readonly CompletionSessionStatus[]; to: CompletionSessionStatus }): Promise<CompletionSession> { const r = await this.pool.query<Row>(`update order_delivery_completion_sessions set status=$3, code_verified_at=case when $3='code_verified' then now() else code_verified_at end, completed_at=case when $3='completed' then now() else completed_at end, updated_at=now() where id=$1 and status=any($2::text[]) returning *`, [input.id, input.from, input.to]); if (r.rows[0] === undefined) throw new CashOnDeliveryTransitionConflictError('Completion session transition conflict'); return session(r.rows[0]) }
}

export class PostgresCashOnDeliveryPaymentRepository implements CashOnDeliveryPaymentRepository {
  constructor(private readonly pool: Pool) {}
  async createAttempt(input: CreateCashOnDeliveryPayment): Promise<CashOnDeliveryPayment> { return inTransaction(this.pool, async client => { const result = await client.query<Row>(`insert into order_cash_on_delivery_payments(id,order_id,session_id,merchant_id,driver_id,attempt_no,stripe_account_id,amount_cents,currency,status,capture_idempotency_key,create_idempotency_key,reader_type,reader_serial,terminal_location_id) select $1,$2,$3,$4,$5,coalesce(max(attempt_no),0)+1,$6,$7,$8,$9,$10,$11,$12,$13,$14 from order_cash_on_delivery_payments where order_id=$2 returning *`, [input.id,input.orderId,input.sessionId,input.merchantId,input.driverId,input.stripeAccountId,input.amountCents,input.currency,input.status,input.captureIdempotencyKey,input.createIdempotencyKey,input.readerType,input.readerSerial,input.terminalLocationId]); return payment(result.rows[0]!) }) }
  async findByOrderId(orderId: string): Promise<CashOnDeliveryPayment | null> { const r = await this.pool.query<Row>('select * from order_cash_on_delivery_payments where order_id=$1 order by attempt_no desc limit 1', [orderId]); return r.rows[0] === undefined ? null : payment(r.rows[0]) }
  async findByPaymentIntentId(paymentIntentId: string): Promise<CashOnDeliveryPayment | null> { const r = await this.pool.query<Row>('select * from order_cash_on_delivery_payments where stripe_payment_intent_id=$1', [paymentIntentId]); return r.rows[0] === undefined ? null : payment(r.rows[0]) }
  async transition(input: { id: string; from: readonly CashOnDeliveryPaymentStatus[]; to: CashOnDeliveryPaymentStatus; stripePaymentIntentId?: string; stripeChargeId?: string; failureCode?: string | null; declineCode?: string | null }): Promise<CashOnDeliveryPayment> { const r = await this.pool.query<Row>(`update order_cash_on_delivery_payments set status=$3, stripe_payment_intent_id=coalesce($4,stripe_payment_intent_id), stripe_charge_id=coalesce($5,stripe_charge_id), failure_code=$6, decline_code=$7, authorized_at=case when $3='authorized' then now() else authorized_at end, captured_at=case when $3='captured' then now() else captured_at end, failed_at=case when $3='failed' then now() else failed_at end, canceled_at=case when $3='canceled' then now() else canceled_at end, updated_at=now() where id=$1 and status=any($2::text[]) returning *`, [input.id,input.from,input.to,input.stripePaymentIntentId ?? null,input.stripeChargeId ?? null,input.failureCode ?? null,input.declineCode ?? null]); if (r.rows[0] === undefined) throw new CashOnDeliveryTransitionConflictError('Cash on delivery payment transition conflict'); return payment(r.rows[0]) }
}

export class PostgresMerchantTerminalLocationRepository implements MerchantTerminalLocationRepository { constructor(private readonly pool: Pool) {} async findByMerchantId(merchantId: string): Promise<MerchantTerminalLocation | null> { const r = await this.pool.query<Row>('select * from merchant_terminal_locations where merchant_id=$1',[merchantId]); return r.rows[0] === undefined ? null : { merchantId: String(r.rows[0].merchant_id), stripeAccountId: String(r.rows[0].stripe_account_id), terminalLocationId: String(r.rows[0].terminal_location_id) } } async save(v: MerchantTerminalLocation): Promise<MerchantTerminalLocation> { const r=await this.pool.query<Row>('insert into merchant_terminal_locations(merchant_id,stripe_account_id,terminal_location_id) values($1,$2,$3) on conflict(merchant_id) do update set stripe_account_id=excluded.stripe_account_id, terminal_location_id=excluded.terminal_location_id returning *',[v.merchantId,v.stripeAccountId,v.terminalLocationId]); return { merchantId:String(r.rows[0]!.merchant_id),stripeAccountId:String(r.rows[0]!.stripe_account_id),terminalLocationId:String(r.rows[0]!.terminal_location_id) } } }
export class PostgresMerchantConnectRepository implements MerchantConnectRepository { constructor(private readonly pool: Pool) {} async findByMerchantId(merchantId:string):Promise<MerchantConnect|null>{const r=await this.pool.query<Row>('select * from merchant_stripe_connect where merchant_id=$1',[merchantId]); return r.rows[0]===undefined?null:connect(r.rows[0])} async save(v:MerchantConnect):Promise<MerchantConnect>{const r=await this.pool.query<Row>('insert into merchant_stripe_connect(merchant_id,merchant_configured_at,card_payments_status,cartes_bancaires_status,requirements_count,last_synced_at) values($1,$2,$3,$4,$5,$6) on conflict(merchant_id) do update set merchant_configured_at=excluded.merchant_configured_at,card_payments_status=excluded.card_payments_status,cartes_bancaires_status=excluded.cartes_bancaires_status,requirements_count=excluded.requirements_count,last_synced_at=excluded.last_synced_at,updated_at=now() returning *',[v.merchantId,v.merchantConfiguredAt,v.cardPaymentsStatus,v.cartesBancairesStatus,v.requirementsCount,v.lastSyncedAt]);return connect(r.rows[0]!)}}
function connect(r:Row):MerchantConnect{return {merchantId:String(r.merchant_id),merchantConfiguredAt:r.merchant_configured_at as Date|null,cardPaymentsStatus:r.card_payments_status as MerchantConnect['cardPaymentsStatus'],cartesBancairesStatus:r.cartes_bancaires_status as MerchantConnect['cartesBancairesStatus'],requirementsCount:Number(r.requirements_count),lastSyncedAt:r.last_synced_at as Date|null}}
