import type { FastifyInstance } from 'fastify'
import { ZodError, z } from 'zod'
import type { DeleteAccountDocumentUseCase, GetAccountDocumentSignedUrlUseCase, Owner, UploadAccountDocumentUseCase } from '../../application/account-documents.js'
import type { AccountDocumentRepository } from '../../application/account-documents.js'
const documentTypeSchema = z.enum(['identity_document', 'business_registration_document'])
const owner = (request: { authUser?: { id: string; role: string } }, role: 'driver' | 'merchant'): Owner | null => request.authUser?.role === role ? { kind: role, id: request.authUser.id } : null
export async function registerAccountDocumentHttpRoutes(app: FastifyInstance, options: { documents: { upload: UploadAccountDocumentUseCase['execute']; list(owner: Owner): ReturnType<AccountDocumentRepository['list']>; signedUrl: GetAccountDocumentSignedUrlUseCase['execute']; delete: DeleteAccountDocumentUseCase['execute'] } }): Promise<void> {
 for (const role of ['driver', 'merchant'] as const) { const base = `/api/v1/${role}s/me/documents`
  app.get(base, async (request, reply) => { const account = owner(request, role); if (account === null) return reply.code(403).send({ error: 'ForbiddenError', correlationId: request.correlationId }); const documents = await options.documents.list(account); return reply.send({ documents: documents.map(d => ({ documentType: d.documentType, originalFilename: d.originalFilename, uploadedAt: d.uploadedAt })) }) })
  app.post(base, async (request, reply) => { try { const account = owner(request, role); if (account === null) return reply.code(403).send({ error: 'ForbiddenError', correlationId: request.correlationId }); const file = await request.file(); if (file === undefined) return reply.code(400).send({ error: 'ValidationError', correlationId: request.correlationId }); const typeField = file.fields.documentType; const raw = Array.isArray(typeField) ? typeField[0] : typeField; const documentType = documentTypeSchema.parse((raw as { value?: unknown } | undefined)?.value); await options.documents.upload({ owner: account, documentType, content: await file.toBuffer(), contentType: file.mimetype, originalFilename: file.filename || null, correlationId: request.correlationId }); return reply.code(204).send() } catch (error) { if (error instanceof ZodError || error instanceof Error && error.message === 'Invalid account document') return reply.code(400).send({ error: 'ValidationError', correlationId: request.correlationId }); request.log.error({ err: error }, 'Account document upload failed'); return reply.code(500).send({ error: 'InternalServerError', correlationId: request.correlationId }) } })
  app.get(`${base}/:documentType/signed-url`, async (request, reply) => { try { const account = owner(request, role); if (account === null) return reply.code(403).send({ error: 'ForbiddenError', correlationId: request.correlationId }); const type = documentTypeSchema.parse((request.params as { documentType: unknown }).documentType); const url = await options.documents.signedUrl(account, type); return url === null ? reply.code(404).send({ error: 'DocumentNotFoundError', correlationId: request.correlationId }) : reply.send({ url, expiresInSeconds: 300 }) } catch (error) { if (error instanceof ZodError) return reply.code(400).send({ error: 'ValidationError', correlationId: request.correlationId }); throw error } })
  app.delete(`${base}/:documentType`, async (request, reply) => { try { const account = owner(request, role); if (account === null) return reply.code(403).send({ error: 'ForbiddenError', correlationId: request.correlationId }); await options.documents.delete(account, documentTypeSchema.parse((request.params as { documentType: unknown }).documentType), request.correlationId); return reply.code(204).send() } catch (error) { if (error instanceof ZodError) return reply.code(400).send({ error: 'ValidationError', correlationId: request.correlationId }); throw error } })
 }
}
