import type { Pool } from 'pg'
import { inTransaction } from '../../../platform/transaction.js'
import type { AccountDocument, AccountDocumentRepository, DocumentType, Owner } from '../application/account-documents.js'
type Row = { id: string; driver_id: string | null; merchant_id: string | null; document_type: DocumentType; storage_path: string; original_filename: string | null; content_type: AccountDocument['contentType']; size_bytes: number; uploaded_at: Date }
export class PostgresAccountDocumentRepository implements AccountDocumentRepository { public constructor(private readonly pool: Pool) {} private owner(owner: Owner): [string, string] { return owner.kind === 'driver' ? ['driver_id', 'driver'] : ['merchant_id', 'merchant'] } private map(row: Row): AccountDocument { return { id: row.id, owner: row.driver_id === null ? { kind: 'merchant', id: row.merchant_id! } : { kind: 'driver', id: row.driver_id }, documentType: row.document_type, storagePath: row.storage_path, originalFilename: row.original_filename, contentType: row.content_type, sizeBytes: row.size_bytes, uploadedAt: row.uploaded_at } }
 public async replace(d: AccountDocument): Promise<{ replacedStoragePath: string | null }> { const [column] = this.owner(d.owner); return inTransaction(this.pool, async client => { const replaced = await client.query<{ storage_path: string }>(`update account_documents set replaced_at = now() where ${column} = $1 and document_type = $2 and replaced_at is null returning storage_path`, [d.owner.id, d.documentType]); await client.query(`insert into account_documents (id, ${column}, document_type, storage_path, original_filename, content_type, size_bytes, uploaded_at) values ($1,$2,$3,$4,$5,$6,$7,$8)`, [d.id,d.owner.id,d.documentType,d.storagePath,d.originalFilename,d.contentType,d.sizeBytes,d.uploadedAt]); return { replacedStoragePath: replaced.rows[0]?.storage_path ?? null } }) }
 public async list(owner: Owner): Promise<AccountDocument[]> { const [column] = this.owner(owner); const r = await this.pool.query<Row>(`select * from account_documents where ${column} = $1 and replaced_at is null order by uploaded_at desc`, [owner.id]); return r.rows.map(row => this.map(row)) }
 public async findCurrent(owner: Owner, type: DocumentType): Promise<AccountDocument | null> { const [column] = this.owner(owner); const r = await this.pool.query<Row>(`select * from account_documents where ${column} = $1 and document_type = $2 and replaced_at is null`, [owner.id,type]); return r.rows[0] === undefined ? null : this.map(r.rows[0]) }
 public async markReplaced(owner: Owner, type: DocumentType): Promise<AccountDocument | null> { const [column] = this.owner(owner); const r = await this.pool.query<Row>(`update account_documents set replaced_at = now() where ${column} = $1 and document_type = $2 and replaced_at is null returning *`, [owner.id,type]); return r.rows[0] === undefined ? null : this.map(r.rows[0]) } }
