import { afterEach, describe, expect, it, vi } from 'vitest'
import { InseeSireneProvider } from '../../src/modules/merchants/infrastructure/insee-sirene-provider.js'
import { SireneRestrictedError, SiretNotFoundError } from '../../src/modules/merchants/ports/sirene-provider.js'

afterEach(() => vi.unstubAllGlobals())
const response = (body: unknown) => new Response(JSON.stringify(body), { status: 200 })
describe('InseeSireneProvider', () => {
  it('uses the headquarters address for a secondary establishment', async () => { const fetchMock=vi.fn().mockResolvedValueOnce(response({etablissement:{siret:'12345678900012',siren:'123456789',etablissementSiege:false,periodesEtablissement:[{dateFin:null,etatAdministratifEtablissement:'A'}],uniteLegale:{nicSiegeUniteLegale:'00099',denominationUniteLegale:'ACME SAS',etatAdministratifUniteLegale:'A'}}})).mockResolvedValueOnce(response({etablissement:{siret:'12345678900099',siren:'123456789',etablissementSiege:true,numeroVoieEtablissement:'50',typeVoieEtablissement:'rue',libelleVoieEtablissement:'du Siege',codePostalEtablissement:'75001',libelleCommuneEtablissement:'Paris'}}));vi.stubGlobal('fetch',fetchMock);const result=await new InseeSireneProvider('secret','https://example.test').lookupBySiret('12345678900012');expect(fetchMock).toHaveBeenCalledTimes(2);expect(result.legalName).toBe('ACME SAS');expect(result.legalAddress.line1).toBe('50 rue du Siege') })
  it('builds an entrepreneur individuel legal name', async () => { vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response({etablissement:{siret:'12345678900012',siren:'123456789',etablissementSiege:true,numeroVoieEtablissement:'1',typeVoieEtablissement:'rue',libelleVoieEtablissement:'Test',codePostalEtablissement:'01000',libelleCommuneEtablissement:'Bourg',periodesEtablissement:[{dateFin:null,etatAdministratifEtablissement:'A'}],uniteLegale:{prenomUsuelUniteLegale:'Marie',nomUniteLegale:'Martin',etatAdministratifUniteLegale:'A'}}})));const result=await new InseeSireneProvider('secret','https://example.test').lookupBySiret('12345678900012');expect(result.legalName).toBe('Marie Martin') })
  it('maps the nested Sirene 3.11 establishment address', async () => { vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response({etablissement:{siret:'12345678900012',siren:'123456789',etablissementSiege:true,adresseEtablissement:{numeroVoieEtablissement:'12',typeVoieEtablissement:'rue',libelleVoieEtablissement:'des Tests',codePostalEtablissement:'01000',libelleCommuneEtablissement:'Bourg-en-Bresse',codeCommuneEtablissement:'01053'},periodesEtablissement:[{dateFin:null,etatAdministratifEtablissement:'A'}],uniteLegale:{denominationUniteLegale:'ACME SAS',etatAdministratifUniteLegale:'A'}}})));const result=await new InseeSireneProvider('secret','https://example.test').lookupBySiret('12345678900012');expect(result.legalAddress).toMatchObject({line1:'12 rue des Tests',postalCode:'01000',city:'Bourg-en-Bresse',communeCode:'01053'}) })
  it('does not prefill partially disseminated information (P)', async () => { const fetchMock=vi.fn().mockResolvedValue(response({etablissement:{siret:'12345678900012',siren:'123456789',etablissementSiege:false,statutDiffusionEtablissement:'P',uniteLegale:{statutDiffusionUniteLegale:'P',nicSiegeUniteLegale:'00099'}}}));vi.stubGlobal('fetch',fetchMock);await expect(new InseeSireneProvider('secret','https://example.test').lookupBySiret('12345678900012')).rejects.toBeInstanceOf(SireneRestrictedError);expect(fetchMock).toHaveBeenCalledTimes(1) })
  it('maps a not found response', async () => { vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('',{status:404})));await expect(new InseeSireneProvider('secret','https://example.test').lookupBySiret('12345678900012')).rejects.toBeInstanceOf(SiretNotFoundError) })
})
