import { describe, expect, it } from 'vitest'
import { isMerchantLegalInformationComplete, isValidSiret, LookupMerchantLegalInformationUseCase, normalizeSiret, UpdateMerchantLegalInformationUseCase } from '../../src/modules/merchants/application/legal-information.js'
import { SireneProviderResponseError, SireneRestrictedError, SireneUnavailableError, SiretNotFoundError, UnavailableSireneProvider, type PostalAddress, type SireneLegalInformation, type SireneProvider } from '../../src/modules/merchants/ports/sirene-provider.js'
import type { MerchantLegalInformation, MerchantLegalInformationPatch, MerchantLegalInformationRepository, MerchantRepository } from '../../src/modules/merchants/ports/merchant-repository.js'
import type { Merchant } from '../../src/modules/merchants/domain/merchant.js'

const address: PostalAddress = { line1: '1 rue de la Paix', line2: null, postalCode: '75001', city: 'Paris', countryCode: 'FR', communeCode: '75056' }
const merchant = { id: 'merchant-1', name: 'Test', zoneId: null, address: null, phonePrimary: null, phoneSecondary: null, logoUrl: null, lat: null, lng: null, onboardingCompleted: false }
class Merchants implements MerchantRepository { public async findById(){return merchant}; public async createIncomplete(){return}; public async updateInformation(): Promise<Merchant>{throw new Error('unused')}; public async updateLogoUrl(): Promise<Merchant>{throw new Error('unused')} }
class LegalRepository implements MerchantLegalInformationRepository { public value: MerchantLegalInformation | null = null; public async findLegalInformation(){return this.value}; public async upsertLegalInformation(patch: MerchantLegalInformationPatch): Promise<MerchantLegalInformation>{ const value: MerchantLegalInformation={...patch,sireneVerifiedAt:patch.sireneVerificationStatus==='verified'?new Date():null}; this.value=value; return value } }
class Provider implements SireneProvider { public calls:string[]=[]; public constructor(private readonly result: SireneLegalInformation | Error){} public async lookupBySiret(siret:string){this.calls.push(siret);if(this.result instanceof Error)throw this.result;return this.result} }
const command = { siret: '732 829 320 00074', legalName: 'ACME SAS', legalAddress: address }

describe('merchant legal information', () => {
  it('normalizes and validates a SIRET with Luhn', () => { expect(normalizeSiret('732 829 320-00074')).toBe('73282932000074'); expect(isValidSiret('73282932000074')).toBe(true); expect(isValidSiret('73282932000075')).toBe(false); expect(isValidSiret('123')).toBe(false) })
  it('marks successful Sirene data verified', async () => { const legal=new LegalRepository(); const provider=new Provider({siret:'73282932000074',siren:'732829320',legalName:'ACME SAS',legalAddress:address,establishmentActive:true,legalUnitActive:true}); const result=await new UpdateMerchantLegalInformationUseCase(new Merchants(),legal,provider).execute('merchant-1',command);expect(result.sireneVerificationStatus).toBe('verified');expect(result.sireneVerifiedAt).not.toBeNull() })
  it('permits manual save after Sirene unavailability or restriction', async () => { for (const error of [new SireneUnavailableError(),new SireneRestrictedError()]) { const legal=new LegalRepository();const result=await new UpdateMerchantLegalInformationUseCase(new Merchants(),legal,new Provider(error)).execute('merchant-1',command);expect(result.sireneVerificationStatus).toBe(error instanceof SireneUnavailableError?'unavailable':'restricted') } })
  it('permits manual save when Sirene returns a malformed technical response', async () => { const legal=new LegalRepository();const result=await new UpdateMerchantLegalInformationUseCase(new Merchants(),legal,new Provider(new SireneProviderResponseError())).execute('merchant-1',command);expect(result.sireneVerificationStatus).toBe('unavailable') })
  it('uses unavailable semantics when no Insee key is configured', async () => { const legal=new LegalRepository();const result=await new UpdateMerchantLegalInformationUseCase(new Merchants(),legal,new UnavailableSireneProvider()).execute('merchant-1',command);expect(result.sireneVerificationStatus).toBe('unavailable') })
  it('does not persist an explicitly unknown SIRET', async () => { const legal=new LegalRepository();await expect(new UpdateMerchantLegalInformationUseCase(new Merchants(),legal,new Provider(new SiretNotFoundError())).execute('merchant-1',command)).rejects.toBeInstanceOf(SiretNotFoundError);expect(legal.value).toBeNull() })
  it('returns lookup data without a repository mutation', async () => { const legal=new LegalRepository();const provider=new Provider({siret:'73282932000074',siren:'732829320',legalName:'ACME SAS',legalAddress:address,establishmentActive:true,legalUnitActive:true});const result=await new LookupMerchantLegalInformationUseCase(new Merchants(),provider).execute('merchant-1','732 829 320 00074');expect(result.siren).toBe('732829320');expect(legal.value).toBeNull() })
  it('triggers once after a successful save and preserves buyer reference semantics', async () => { const legal = new LegalRepository(); legal.value = { merchantId: 'merchant-1', siret: '73282932000074', siren: '732829320', legalName: 'Old', legalAddress: address, billingAddress: null, vatNumber: null, buyerReference: 'old', sireneVerificationStatus: 'verified', sireneVerifiedAt: new Date() }; const calls: Array<{ merchantId: string; siren: string }> = []; const provider = new Provider({ siret: '73282932000074', siren: '732829320', legalName: 'ACME SAS', legalAddress: address, establishmentActive: true, legalUnitActive: true }); const useCase = new UpdateMerchantLegalInformationUseCase(new Merchants(), legal, provider, { onLegalInformationUpdated: (input) => calls.push(input) }); expect((await useCase.execute('merchant-1', command)).buyerReference).toBe('old'); expect((await useCase.execute('merchant-1', { ...command, buyerReference: 'new' })).buyerReference).toBe('new'); expect((await useCase.execute('merchant-1', { ...command, buyerReference: null })).buyerReference).toBeNull(); expect(calls).toEqual([{ merchantId: 'merchant-1', siren: '732829320' }, { merchantId: 'merchant-1', siren: '732829320' }, { merchantId: 'merchant-1', siren: '732829320' }]) })
  it('does not trigger before validation or an unknown SIRET failure', async () => { const calls: unknown[] = []; const trigger = { onLegalInformationUpdated: (input: unknown) => calls.push(input) }; await expect(new UpdateMerchantLegalInformationUseCase(new Merchants(), new LegalRepository(), new Provider(new SiretNotFoundError()), trigger).execute('merchant-1', command)).rejects.toBeInstanceOf(SiretNotFoundError); await expect(new UpdateMerchantLegalInformationUseCase(new Merchants(), new LegalRepository(), new Provider(new SiretNotFoundError()), trigger).execute('merchant-1', { ...command, siret: 'bad' })).rejects.toBeInstanceOf(Error); expect(calls).toEqual([]) })
  it('derives section completeness independently', () => { expect(isMerchantLegalInformationComplete(null)).toBe(false); const complete: MerchantLegalInformation={merchantId:'merchant-1',siret:'73282932000074',siren:'732829320',legalName:'ACME SAS',legalAddress:address,billingAddress:null,vatNumber:null,buyerReference:null,sireneVerificationStatus:'unavailable',sireneVerifiedAt:null};expect(isMerchantLegalInformationComplete(complete)).toBe(true);expect(isMerchantLegalInformationComplete({...complete,legalName:' '})).toBe(false) })
})
