import { createHash } from 'node:crypto'
import { describe, expect, it, vi } from 'vitest'
import { AcceptDriverEInvoiceMandateUseCase, DriverLegalInformationRequiredError, MandateTemplateNotConfiguredError } from '../../src/modules/invoices/application/accept-driver-einvoice-mandate.js'
import type { CurrentDriverEInvoiceMandate } from '../../src/modules/invoices/ports/driver-einvoice-mandate-repository.js'
const image = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL9JQAAAABJRU5ErkJggg=='
const live = { professionalName: 'Pro', siret: '12345678900012', siren: '123456789', legalAddress: { line1: '1 rue', line2: null, postalCode: '01000', city: 'Bourg', countryCode: 'FR' }, vatNumber: null, vatRegime: null, legalForm: null }
const template = { version: 1, text: 'Mandat', textSha256: createHash('sha256').update('Mandat').digest('hex') }
const existing: CurrentDriverEInvoiceMandate = { id: 'old', driverId: 'driver', snapshot: { firstNameSnapshot: 'Jean', lastNameSnapshot: 'Martin', siren: live.siren, legalNameSnapshot: 'Pro', nameSnapshot: 'Jean Martin', professionalNameSnapshot: 'Pro', siretSnapshot: live.siret, legalAddressLine1Snapshot: '1 rue', legalAddressLine2Snapshot: null, legalAddressPostalCodeSnapshot: '01000', legalAddressCitySnapshot: 'Bourg', legalAddressCountryCodeSnapshot: 'FR', vatNumberSnapshot: null, vatRegimeSnapshot: null, legalFormSnapshot: null }, mandateTemplateVersion: 1, mandateTextHash: template.textSha256, acceptedAt: new Date(), signedPdfStoragePath: 'old', signedPdfSha256: 'hash', providerVerificationStatus: 'not_submitted', submissionStatus: 'prepared', lastError: null }
function setup(current: CurrentDriverEInvoiceMandate | null = null, legal: typeof live | null = live, currentTemplate: typeof template | null = template, profile: { firstName: string; lastName: string } | null = { firstName: 'Jean', lastName: 'Martin' }) { const mandates = { findCurrent: vi.fn().mockResolvedValue(current), insert: vi.fn().mockImplementation(async (value) => ({ ...existing, id: value.id, driverId: value.driverId, snapshot: value.snapshot })) }; const renderer = { render: vi.fn().mockResolvedValue(Buffer.from('pdf')) }; const storage = { uploadMandatePdf: vi.fn().mockResolvedValue('path'), downloadMandatePdf: vi.fn(), createSignedMandatePdfUrl: vi.fn() }; return { mandates, renderer, storage, useCase: new AcceptDriverEInvoiceMandateUseCase(mandates, { findCurrent: vi.fn().mockResolvedValue(currentTemplate) }, renderer, storage, { findDriverLegalInformation: vi.fn().mockResolvedValue(legal) }, { findDriverProfile: vi.fn().mockResolvedValue(profile) }, { findPlatformLegalIdentity: vi.fn().mockResolvedValue({ legalName: 'Loc', siren: '987654321', siret: null, addressLine1: 'x', addressLine2: null, postalCode: '1', city: 'x', countryCode: 'FR' }) }, () => new Date('2026-01-01T00:00:00Z'), () => 'id') } }
describe('AcceptDriverEInvoiceMandateUseCase', () => { it('inserts name snapshots once and is idempotent', async () => { const a = setup(); await a.useCase.execute({ driverId: 'driver', signatureImageBase64: image, signerFirstName: ' Jean ', signerLastName: ' Martin ' }); expect(a.renderer.render).toHaveBeenCalledWith(expect.objectContaining({ fields: expect.objectContaining({ driver_first_name: 'Jean', driver_last_name: 'Martin' }) })); expect(a.mandates.insert).toHaveBeenCalledWith(expect.objectContaining({ snapshot: expect.objectContaining({ firstNameSnapshot: 'Jean', lastNameSnapshot: 'Martin' }) })); const b = setup(existing); await expect(b.useCase.execute({ driverId: 'driver', signatureImageBase64: image, signerFirstName: 'Jean', signerLastName: 'Martin' })).resolves.toBe(existing); expect(b.renderer.render).not.toHaveBeenCalled(); expect(b.storage.uploadMandatePdf).not.toHaveBeenCalled(); expect(b.mandates.insert).not.toHaveBeenCalled() }); it('fails before rendering for missing legal data, profile, template, and invalid image', async () => { await expect(setup(null, null).useCase.execute({ driverId: 'driver', signatureImageBase64: image, signerFirstName: 'Jean', signerLastName: 'Martin' })).rejects.toBeInstanceOf(DriverLegalInformationRequiredError); await expect(setup(null, live, template, null).useCase.execute({ driverId: 'driver', signatureImageBase64: image, signerFirstName: 'Jean', signerLastName: 'Martin' })).rejects.toBeInstanceOf(DriverLegalInformationRequiredError); await expect(setup(null, live, null).useCase.execute({ driverId: 'driver', signatureImageBase64: image, signerFirstName: 'Jean', signerLastName: 'Martin' })).rejects.toBeInstanceOf(MandateTemplateNotConfiguredError); const a = setup(); await expect(a.useCase.execute({ driverId: 'driver', signatureImageBase64: 'not-a-png', signerFirstName: 'Jean', signerLastName: 'Martin' })).rejects.toThrow(); expect(a.renderer.render).not.toHaveBeenCalled() }) })
