import { describe, expect, it } from 'vitest'
import { DriverEInvoiceReadiness } from '../../src/modules/invoices/application/driver-einvoice-readiness.js'
import { EInvoiceNetworkBeforeSendError, EInvoiceUnknownOutcomeError, retryAt, RunEInvoiceSubmissionsUseCase } from '../../src/modules/invoices/application/run-einvoice-submissions.js'
import { PollEInvoiceEventsUseCase } from '../../src/modules/invoices/application/poll-einvoice-events.js'
import type { EInvoiceWorkRepository, SubmissionWork } from '../../src/modules/invoices/ports/einvoice-work-repository.js'

const work = (): SubmissionWork => ({ id: 'sub', documentKind: 'invoice', documentId: 'invoice', externalId: 'invoice:invoice', attempts: 1, issuerKind: 'locadely', issuerDriverId: null, buyerMerchantId: 'merchant', buyerSiren: '987654321', invoice: { id: 'invoice', number: 'F-1', invoiceTypeCode: '380', issuedAt: new Date(), currencyCode: 'EUR', totalHtCents: 100, totalVatCents: 20, totalTtcCents: 120, buyerReference: null, seller: { legalName: 'S', siren: '123456789', vatNumber: null, addressLine1: 'x', addressLine2: null, postalCode: '1', city: 'x', countryCode: 'FR', electronicAddressScheme: null, electronicAddressValue: null }, buyer: { legalName: 'B', siren: '987654321', vatNumber: null, addressLine1: 'x', addressLine2: null, postalCode: '1', city: 'x', countryCode: 'FR' }, paymentTermsText: 'SEPA', paymentMeansTypeCode: '59', lines: [{ lineNumber: 1, description: 'x', quantity: '1', unit: null, unitPriceHtCents: 100, lineHtCents: 100, lineVatCents: 20, vatRateBps: 2000, vatExemptionReasonText: null }] } })
function repo(): EInvoiceWorkRepository & { calls: string[]; errors: string[] } { const calls: string[] = []; const errors: string[] = []; return { calls, errors, claimDue: async () => [work()], submitted: async () => { calls.push('submitted') }, retryable: async ({ error }) => { calls.push('retryable'); errors.push(error) }, failed: async () => { calls.push('failed') }, unknownOutcome: async () => { calls.push('unknown') } } }
const directory = { resolve: async () => ({ status: 'ready' as const, electronicAddress: { scheme: '0225', value: '987654321' } }) }
const readiness = new DriverEInvoiceReadiness({ hasVerifiedMandate: async () => true })
describe('e-invoice submission worker', () => {
  for (const [name, failure, result] of [['success', null, 'submitted'], ['network before send', new EInvoiceNetworkBeforeSendError('dns'), 'retryable'], ['5xx retry', new EInvoiceNetworkBeforeSendError('HTTP 503'), 'retryable'], ['timeout after send', new EInvoiceUnknownOutcomeError('timeout'), 'unknown'], ['deterministic 4xx fails', new Error('HTTP 422'), 'failed']] as const) {
    it(name, async () => { const r = repo(); const provider = { submitInvoice: async () => { if (failure !== null) throw failure; return { providerDocumentId: '42', contentType: 'application/xml', document: Buffer.from('xml') } }, submitCreditNote: async () => { throw new Error('not used') }, getStatus: async () => ({}), listEvents: async () => ({ events: [], hasAfter: false }), getDocument: async () => ({ content: Buffer.alloc(0), contentType: 'application/pdf' }) }; await new RunEInvoiceSubmissionsUseCase(r, provider, readiness, directory, '0225').execute(); expect(r.calls).toEqual([result]) })
  }
  it('does not submit a driver without a verified mandate and labels it retryable', async () => { const r = repo(); const item = work(); item.issuerKind = 'driver'; item.issuerDriverId = 'driver'; r.claimDue = async () => [item]; let calls = 0; const provider = { submitInvoice: async () => { calls++; throw new Error('should not') }, submitCreditNote: async () => { throw new Error('should not') }, getStatus: async () => ({}), listEvents: async () => ({ events: [], hasAfter: false }), getDocument: async () => ({ content: Buffer.alloc(0), contentType: 'application/pdf' }) }; await new RunEInvoiceSubmissionsUseCase(r, provider, new DriverEInvoiceReadiness({ hasVerifiedMandate: async () => false }), directory, '0225').execute(); expect(calls).toBe(0); expect(r.calls).toEqual(['retryable']); expect(r.errors).toEqual(['not_ready:waiting_for_mandate']) })
  it('resolves the directory once per item and does not submit an unaddressable buyer', async () => { const r = repo(); let resolves = 0; let submits = 0; const provider = { submitInvoice: async () => { submits++; return { providerDocumentId: '42', contentType: 'application/xml', document: Buffer.from('xml') } }, submitCreditNote: async () => { throw new Error('not used') }, getStatus: async () => ({}), listEvents: async () => ({ events: [], hasAfter: false }), getDocument: async () => ({ content: Buffer.alloc(0), contentType: 'application/pdf' }) }; await new RunEInvoiceSubmissionsUseCase(r, provider, readiness, { resolve: async () => { resolves++; return { status: 'not_addressable' as const } } }, '0225').execute(); expect(resolves).toBe(1); expect(submits).toBe(0); expect(r.errors).toEqual(['not_ready:waiting_for_recipient_address']) })
  it('uses exponential retry delays from one minute up to six hours', () => { const now = new Date('2026-01-01T00:00:00Z'); expect(retryAt(1, now).getTime() - now.getTime()).toBe(60_000); expect(retryAt(2, now).getTime() - now.getTime()).toBe(120_000); expect(retryAt(99, now).getTime() - now.getTime()).toBe(21_600_000) })
})
describe('event polling', () => it('consumes all pages and advances the cursor once per page', async () => { const requested: number[] = []; const applied: number[][] = []; const provider = { listEvents: async (after: number) => { requested.push(after); return after === 7 ? { events: [{ id: 8, invoiceId: '42', statusCode: 'fr:200', statusText: '', createdAt: new Date() }], hasAfter: true } : { events: [{ id: 9, invoiceId: '42', statusCode: 'fr:205', statusText: '', createdAt: new Date() }], hasAfter: false } } }; const repository = { cursor: async () => 7, applyEvents: async ({ events }: { events: Array<{ id: number }> }) => { applied.push(events.map((event) => event.id)) } }; await new PollEInvoiceEventsUseCase(repository, provider as never).execute(); expect(requested).toEqual([7, 8]); expect(applied).toEqual([[8], [9]]) }))
