import { describe, expect, it } from 'vitest'
import { GetDriverEInvoiceMandateStatusUseCase } from '../../src/modules/invoices/application/get-driver-einvoice-mandate-status.js'
import type { CurrentDriverEInvoiceMandate } from '../../src/modules/invoices/ports/driver-einvoice-mandate-repository.js'
const live = { professionalName: 'Pro', siret: '12345678900012', siren: '123456789', legalAddress: { line1: '1 rue', line2: null, postalCode: '01000', city: 'Bourg', countryCode: 'FR' }, vatNumber: null, vatRegime: null, legalForm: null }
const template = { version: 1, text: '{{driver_first_name}} {{driver_last_name}} {{driver_legal_name}} {{signer_first_name}} {{signer_last_name}} {{signed_at}} {{mandate_version}} {{mandate_reference}} {{handwritten_signature}}', textSha256: 'hash' }
const seller = { legalName: 'Loc', siren: '987654321', siret: null, addressLine1: 'x', addressLine2: null, postalCode: '1', city: 'x', countryCode: 'FR' }
const mandate: CurrentDriverEInvoiceMandate = { id: 'id', driverId: 'driver', snapshot: { firstNameSnapshot: 'Jean', lastNameSnapshot: 'Martin', siren: live.siren, legalNameSnapshot: 'Pro', nameSnapshot: 'Jean Martin', professionalNameSnapshot: 'Pro', siretSnapshot: live.siret, legalAddressLine1Snapshot: '1 rue', legalAddressLine2Snapshot: null, legalAddressPostalCodeSnapshot: '01000', legalAddressCitySnapshot: 'Bourg', legalAddressCountryCodeSnapshot: 'FR', vatNumberSnapshot: null, vatRegimeSnapshot: null, legalFormSnapshot: null }, mandateTemplateVersion: 1, mandateTextHash: 'hash', acceptedAt: new Date(), signedPdfStoragePath: 'path', signedPdfSha256: 'hash', providerVerificationStatus: 'not_submitted', submissionStatus: 'retryable', lastError: 'network' }
function status(input: { current?: CurrentDriverEInvoiceMandate | null; legal?: typeof live | null; currentTemplate?: typeof template | null; profile?: { firstName: string; lastName: string } | null; platform?: typeof seller | null } = {}) { return new GetDriverEInvoiceMandateStatusUseCase({ findCurrent: async () => input.current ?? null, insert: async () => mandate }, { findDriverLegalInformation: async () => input.legal === undefined ? live : input.legal }, { findCurrent: async () => input.currentTemplate === undefined ? template : input.currentTemplate }, { findDriverProfile: async () => input.profile === undefined ? { firstName: 'Jean', lastName: 'Martin' } : input.profile }, { findPlatformLegalIdentity: async () => input.platform === undefined ? seller : input.platform }).execute('driver') }
describe('GetDriverEInvoiceMandateStatusUseCase', () => { it('provides a pre-signature preview and blocking reasons', async () => { const ready = await status(); expect(ready).toMatchObject({ blockedReason: null, submissionStatus: null, lastError: null }); expect(ready.previewText).toContain('Jean Martin Pro'); expect(ready.previewText).toContain('[à renseigner à la signature]'); expect(ready.previewText).toContain('[à la signature]'); expect(ready.previewText).toContain('[généré à la signature]'); expect(ready.previewText).toContain('[votre signature]'); await expect(status({ legal: null })).resolves.toMatchObject({ blockedReason: 'legal_information_missing', previewText: null }); await expect(status({ profile: null })).resolves.toMatchObject({ blockedReason: 'driver_name_missing', previewText: null }); await expect(status({ currentTemplate: null })).resolves.toMatchObject({ blockedReason: 'template_not_configured', previewText: null }); await expect(status({ platform: null })).resolves.toMatchObject({ blockedReason: 'platform_identity_missing', previewText: null }) }); it('keeps signed mandates distinct and exposes submission state', async () => { const result = await status({ current: mandate }); expect(result).toMatchObject({ previewText: null, submissionStatus: 'retryable', lastError: 'network', drift: { drifted: false } }); expect((await status({ current: mandate, legal: { ...live, siret: '12345678900013' } })).drift).toEqual({ drifted: true, changedFields: ['siret'] }) }) })
