import { describe, expect, it } from 'vitest'
import { RefreshBuyerElectronicAddressUseCase } from '../../src/modules/invoices/application/resolve-buyer-electronic-address.js'
import type { DirectoryCacheEntry, EInvoiceDirectoryCacheRepository } from '../../src/modules/invoices/ports/einvoice-directory-cache.js'
import type { FrenchDirectoryProvider } from '../../src/modules/invoices/ports/french-directory-provider.js'
class Cache implements EInvoiceDirectoryCacheRepository { public entry: DirectoryCacheEntry | null = null; public writes: DirectoryCacheEntry[] = []; public async read(){ return this.entry }; public async upsert(_id: string, entry: DirectoryCacheEntry){ this.entry = entry; this.writes.push(entry) } }
class Directory implements FrenchDirectoryProvider { public calls = 0; public failure = false; public async lookupBySiren(){ this.calls++; if (this.failure) throw new Error('down'); return [{ identifier: '0225:853322915', isActive: true }] } }
describe('buyer electronic address refresh', () => {
  it('uses a fresh matching cache entry without networking', async () => { const cache = new Cache(); cache.entry = { siren: '123456789', resolution: { status: 'not_addressable' }, checkedAt: new Date('2026-01-01T00:00:00Z') }; const directory = new Directory(); expect(await new RefreshBuyerElectronicAddressUseCase(cache, directory).resolve('m', '123456789', new Date('2026-01-01T01:00:00Z'))).toEqual({ status: 'not_addressable' }); expect(directory.calls).toBe(0) })
  it('refreshes stale or mismatched cache entries', async () => { for (const entry of [{ siren: '123456789', resolution: { status: 'not_addressable' as const }, checkedAt: new Date('2025-12-30') }, { siren: '000000000', resolution: { status: 'not_addressable' as const }, checkedAt: new Date('2026-01-01') }]) { const cache = new Cache(); cache.entry = entry; const directory = new Directory(); await new RefreshBuyerElectronicAddressUseCase(cache, directory).resolve('m', '123456789', new Date('2026-01-01T01:00:00Z')); expect(directory.calls).toBe(1) } })
  it('persists lookup failures and refresh always bypasses a fresh cache', async () => { const cache = new Cache(); cache.entry = { siren: '123456789', resolution: { status: 'not_addressable' }, checkedAt: new Date('2026-01-01') }; const directory = new Directory(); directory.failure = true; const useCase = new RefreshBuyerElectronicAddressUseCase(cache, directory); expect(await useCase.refresh('m', '123456789', new Date('2026-01-01T01:00:01Z'))).toEqual({ status: 'lookup_failed' }); expect(cache.writes.at(-1)?.resolution).toEqual({ status: 'lookup_failed' }); expect(directory.calls).toBe(1) })
})
