import type { Pool } from 'pg'
import { inTransaction } from '../../../platform/transaction.js'
import type { CurrentDriverEInvoiceMandate, DriverEInvoiceMandateRepository, DriverEInvoiceMandateSnapshot, ProviderVerificationStatus } from '../ports/driver-einvoice-mandate-repository.js'
export class DriverEInvoiceMandateAlreadyExistsError extends Error { public constructor() { super('A current electronic invoicing mandate already exists for this driver'); this.name = 'DriverEInvoiceMandateAlreadyExistsError' } }
type Row = { id: string; driver_id: string; grantor_first_name_snapshot: string; grantor_last_name_snapshot: string; grantor_siren: string; grantor_legal_name_snapshot: string; grantor_name_snapshot: string; grantor_professional_name_snapshot: string; grantor_siret_snapshot: string; grantor_legal_address_line1_snapshot: string; grantor_legal_address_line2_snapshot: string | null; grantor_legal_address_postal_code_snapshot: string; grantor_legal_address_city_snapshot: string; grantor_legal_address_country_code_snapshot: string; grantor_vat_number_snapshot: string | null; grantor_vat_regime_snapshot: DriverEInvoiceMandateSnapshot['vatRegimeSnapshot']; grantor_legal_form_snapshot: string | null; mandate_template_version: number; mandate_text_hash: string; accepted_at: Date; signed_pdf_storage_path: string; signed_pdf_sha256: string; provider_verification_status: ProviderVerificationStatus; submission_status: CurrentDriverEInvoiceMandate['submissionStatus']; last_error: string | null }
const returning = 'id, driver_id, grantor_first_name_snapshot, grantor_last_name_snapshot, grantor_siren, grantor_legal_name_snapshot, grantor_name_snapshot, grantor_professional_name_snapshot, grantor_siret_snapshot, grantor_legal_address_line1_snapshot, grantor_legal_address_line2_snapshot, grantor_legal_address_postal_code_snapshot, grantor_legal_address_city_snapshot, grantor_legal_address_country_code_snapshot, grantor_vat_number_snapshot, grantor_vat_regime_snapshot, grantor_legal_form_snapshot, mandate_template_version, mandate_text_hash, accepted_at, signed_pdf_storage_path, signed_pdf_sha256, provider_verification_status, submission_status, last_error'
function map(row: Row): CurrentDriverEInvoiceMandate { return { id: row.id, driverId: row.driver_id, snapshot: { firstNameSnapshot: row.grantor_first_name_snapshot, lastNameSnapshot: row.grantor_last_name_snapshot, siren: row.grantor_siren, legalNameSnapshot: row.grantor_legal_name_snapshot, nameSnapshot: row.grantor_name_snapshot, professionalNameSnapshot: row.grantor_professional_name_snapshot, siretSnapshot: row.grantor_siret_snapshot, legalAddressLine1Snapshot: row.grantor_legal_address_line1_snapshot, legalAddressLine2Snapshot: row.grantor_legal_address_line2_snapshot, legalAddressPostalCodeSnapshot: row.grantor_legal_address_postal_code_snapshot, legalAddressCitySnapshot: row.grantor_legal_address_city_snapshot, legalAddressCountryCodeSnapshot: row.grantor_legal_address_country_code_snapshot, vatNumberSnapshot: row.grantor_vat_number_snapshot, vatRegimeSnapshot: row.grantor_vat_regime_snapshot, legalFormSnapshot: row.grantor_legal_form_snapshot }, mandateTemplateVersion: row.mandate_template_version, mandateTextHash: row.mandate_text_hash, acceptedAt: row.accepted_at, signedPdfStoragePath: row.signed_pdf_storage_path, signedPdfSha256: row.signed_pdf_sha256, providerVerificationStatus: row.provider_verification_status, submissionStatus: row.submission_status, lastError: row.last_error } }
function isCurrentUniqueViolation(error: unknown): boolean { return typeof error === 'object' && error !== null && 'code' in error && (error as { code?: string }).code === '23505' && 'constraint' in error && (error as { constraint?: string }).constraint === 'driver_einvoice_mandates_driver_current_idx' }
export class PostgresDriverEInvoiceMandateRepository implements DriverEInvoiceMandateRepository {
  public constructor(private readonly pool: Pool) {}
  public async findCurrent(driverId: string): Promise<CurrentDriverEInvoiceMandate | null> { const row = (await this.pool.query<Row>(`select ${returning} from driver_einvoice_mandates where driver_id=$1 and revoked_at is null`, [driverId])).rows[0]; return row === undefined ? null : map(row) }
  public async insert(input: { id: string; driverId: string; snapshot: DriverEInvoiceMandateSnapshot; mandateTemplateVersion: number; mandateTextHash: string; acceptedAt: Date; acceptanceEvidence: unknown; signedPdfStoragePath: string; signedPdfSha256: string }): Promise<CurrentDriverEInvoiceMandate> {
    try { return await inTransaction(this.pool, async (client) => { const s = input.snapshot; const row = (await client.query<Row>(`insert into driver_einvoice_mandates (id,driver_id,grantor_first_name_snapshot,grantor_last_name_snapshot,grantor_siren,grantor_legal_name_snapshot,grantor_name_snapshot,grantor_professional_name_snapshot,grantor_siret_snapshot,grantor_legal_address_line1_snapshot,grantor_legal_address_line2_snapshot,grantor_legal_address_postal_code_snapshot,grantor_legal_address_city_snapshot,grantor_legal_address_country_code_snapshot,grantor_vat_number_snapshot,grantor_vat_regime_snapshot,grantor_legal_form_snapshot,mandate_template_version,mandate_text_hash,accepted_at,acceptance_method,acceptance_evidence,signed_pdf_storage_path,signed_pdf_sha256,provider) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,'mobile_drawn_signature',$21::jsonb,$22,$23,'superpdp') returning ${returning}`, [input.id,input.driverId,s.firstNameSnapshot,s.lastNameSnapshot,s.siren,s.legalNameSnapshot,s.nameSnapshot,s.professionalNameSnapshot,s.siretSnapshot,s.legalAddressLine1Snapshot,s.legalAddressLine2Snapshot,s.legalAddressPostalCodeSnapshot,s.legalAddressCitySnapshot,s.legalAddressCountryCodeSnapshot,s.vatNumberSnapshot,s.vatRegimeSnapshot,s.legalFormSnapshot,input.mandateTemplateVersion,input.mandateTextHash,input.acceptedAt,JSON.stringify(input.acceptanceEvidence),input.signedPdfStoragePath,input.signedPdfSha256])).rows[0]; if (row === undefined) throw new Error('Mandate insert did not return a row'); return map(row) }) } catch (error) { if (isCurrentUniqueViolation(error)) throw new DriverEInvoiceMandateAlreadyExistsError(); throw error }
  }
}
