import { randomUUID } from 'node:crypto'
import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest'
import { config } from '../../src/platform/config.js'
import { pool } from '../../src/platform/db.js'
import { createOrdersModule } from '../../src/modules/orders/public.js'
import { DeliveryCompletionUseCases, CompletionHttpError } from '../../src/modules/cash-on-delivery/public.js'
import { FakeConnectPaymentsProvider } from '../support/fake-connect-payments-provider.js'
import { deleteTestOrders } from '../support/cleanup-orders.js'
import { lockSeedFixture } from '../support/exclusive-fixture-lock.js'

const merchantId='22222222-2222-2222-2222-222222222222',driverId='33333333-3333-3333-3333-333333333333',otherDriverId='44444444-4444-4444-4444-444444444444';const ids:string[]=[]
const orders=createOrdersModule(pool,config.OSRM_URL,async()=>({lat:46.2,lng:5.2}),undefined,{increment:async()=>undefined,decrement:async()=>undefined})
async function order(cod=true){const merchant=await pool.query<{id:string;name:string;zone_id:string;address:string}>("select id,name,zone_id,address from merchants where id=$1",[merchantId]);const m=merchant.rows[0]!;const zone=await pool.query<{id:string}>('select id from zones where id=$1',[m.zone_id]);const made=await orders.createOrder({merchant:{id:m.id,name:m.name,zoneId:m.zone_id,address:m.address,phonePrimary:'0',phoneSecondary:null,logoUrl:null,lat:46.2,lng:5.2,onboardingCompleted:true},zone:{id:zone.rows[0]!.id,name:'z',centerLat:46.2,centerLng:5.2,radiusKm:10},customerName:'C',customerPhone:'0600000000',deliveryAddress:'D',deliveryLat:46.21,deliveryLng:5.21,pickupScheduledAt:{mode:'asap'},cashOnDelivery:cod?{amountCents:5000}:undefined});ids.push(made.id);const assigned=await orders.assignOrder({orderId:made.id,driverId,expectedVersion:made.version,actor:{type:'driver',id:driverId}});return orders.collectOrder({orderId:made.id,driverId,expectedVersion:assigned.version,actor:{type:'driver',id:driverId}})}
async function code(id:string){return (await orders.getMerchantOrders(merchantId)).find(x=>x.id===id)!.deliveryCode!}
function use(fake=new FakeConnectPaymentsProvider(),allow=true){return {fake,uc:new DeliveryCompletionUseCases(pool,orders,fake,async()=> 'acct_test',async()=>({id:merchantId,name:'M',zoneId:'z',address:'A',phonePrimary:'0',phoneSecondary:null,logoUrl:null,lat:46.2,lng:5.2,onboardingCompleted:true}),async()=>({merchantId,siret:'1',siren:'1',legalName:'M',legalAddress:{line1:'1 rue',line2:null,postalCode:'01000',city:'Bourg',countryCode:'FR',communeCode:null},billingAddress:null,vatNumber:null,buyerReference:null,sireneVerificationStatus:'verified',sireneVerifiedAt:null}),allow)}}
async function start(uc:DeliveryCompletionUseCases,o:{id:string;version:number}){return uc.create({orderId:o.id,driverId,expectedVersion:o.version,deliveryCode:await code(o.id),readerFamily:'simulated_bluetooth',correlationId:randomUUID()}) as Promise<{sessionId:string;payment:{id:string}}>} 
let unlockFixture: () => Promise<void>
beforeAll(async () => { unlockFixture = await lockSeedFixture(pool) }, 180_000)
afterAll(async () => { await unlockFixture() })
afterEach(async()=>{await deleteTestOrders(pool,ids.splice(0));await pool.query('delete from merchant_terminal_locations where merchant_id=$1',[merchantId])})

describe('COD delivery completion',()=>{
  it('captures exact immutable order snapshot, completes order, writes events/outbox',async()=>{const o=await order();const {uc,fake}=use();const s=await start(uc,o);const pi=[...fake.intents.values()][0]!;expect(pi).toMatchObject({accountId:'acct_test',amountCents:5000,currency:'eur'});fake.authorize(pi.id);await uc.finalize({orderId:o.id,driverId,sessionId:s.sessionId,paymentId:s.payment.id,correlationId:randomUUID()});const r=await pool.query<{status:string;cash_on_delivery_collected_at:Date|null;events:string;outbox:string}>("select o.status,o.cash_on_delivery_collected_at,(select count(*) from order_events where order_id=o.id) events,(select count(*) from outbox_event where aggregate_id=o.id) outbox from orders o where id=$1",[o.id]);expect(r.rows[0]).toMatchObject({status:'COMPLETED'});expect(r.rows[0]!.cash_on_delivery_collected_at).not.toBeNull();expect(Number(r.rows[0]!.events)).toBeGreaterThan(0);expect(Number(r.rows[0]!.outbox)).toBeGreaterThan(0)})
  it('keeps non-COD existing completion path',async()=>{const o=await order(false);const {uc}=use();await expect(start(uc,o)).resolves.toMatchObject({status:'completed'})})
  it('cannot complete COD before captured payment',async()=>{const o=await order();const {uc}=use();await expect(orders.completeOrder({orderId:o.id,driverId,expectedVersion:o.version,proof:{method:'code',code:await code(o.id)},actor:{type:'driver',id:driverId}})).rejects.toMatchObject({name:'CashOnDeliveryPaymentRequired'});await expect(uc.finalize({orderId:o.id,driverId,sessionId:randomUUID(),paymentId:randomUUID(),correlationId:randomUUID()})).rejects.toBeInstanceOf(CompletionHttpError)})
  it('decline cancels, retry makes attempt two without another code, then succeeds',async()=>{const o=await order();const {uc,fake}=use();const s=await start(uc,o);const first=[...fake.intents.values()][0]!;fake.decline(first.id);await expect(uc.finalize({orderId:o.id,driverId,sessionId:s.sessionId,paymentId:s.payment.id,correlationId:randomUUID()})).rejects.toMatchObject({code:'PaymentDeclined',extra:{declineCode:'generic_decline'}});expect(fake.calls.cancelPaymentIntent).toBe(1);const retry=await uc.retry({orderId:o.id,driverId,sessionId:s.sessionId,correlationId:randomUUID()}) as {payment:{id:string}};const second=[...fake.intents.values()][1]!;expect(retry.payment.id).not.toBe(s.payment.id);expect((await pool.query<{attempt_no:number}>('select attempt_no from order_cash_on_delivery_payments where id=$1',[retry.payment.id])).rows[0]!.attempt_no).toBe(2);fake.authorize(second.id);await expect(uc.finalize({orderId:o.id,driverId,sessionId:s.sessionId,paymentId:retry.payment.id,correlationId:randomUUID()})).resolves.toMatchObject({status:'completed'})})
  it('double and concurrent finalize have one capture',async()=>{const o=await order();const {uc,fake}=use();const s=await start(uc,o);fake.authorize('pi_1');const cmd={orderId:o.id,driverId,sessionId:s.sessionId,paymentId:s.payment.id,correlationId:randomUUID()};await uc.finalize(cmd);await expect(uc.finalize(cmd)).resolves.toMatchObject({status:'completed'});expect(fake.calls.capturePaymentIntent).toBe(1)})
  it('unexpected capture state rereads succeeded PI without second capture',async()=>{const o=await order();const {uc,fake}=use();const s=await start(uc,o);fake.authorize('pi_1');fake.unexpectedCapture=true;await expect(uc.finalize({orderId:o.id,driverId,sessionId:s.sessionId,paymentId:s.payment.id,correlationId:randomUUID()})).resolves.toMatchObject({status:'completed'});expect(fake.calls.capturePaymentIntent).toBe(1)})
  it.each([{applicationFeeAmountCents:1},{hasTransferData:true},{hasOnBehalfOf:true},{amountCents:4999},{currency:'usd'},{accountId:'acct_other'},{metadata:{order_id:'bad',payment_id:'bad'}},{captureMethod:'automatic'},{paymentMethodTypes:['card']}])('rejects contaminated PI %#',async contamination=>{const o=await order();const {uc,fake}=use();fake.contamination=contamination;const s=await start(uc,o);fake.authorize('pi_1');await expect(uc.finalize({orderId:o.id,driverId,sessionId:s.sessionId,paymentId:s.payment.id,correlationId:randomUUID()})).rejects.toMatchObject({code:'PaymentNotConfirmed'});expect((await pool.query<{status:string}>('select status from order_cash_on_delivery_payments where id=$1',[s.payment.id])).rows[0]!.status).toBe('unknown')})
  it('rejects wrong driver and simulated reader / inactive card payments before PI',async()=>{const o=await order();const fake=new FakeConnectPaymentsProvider();const {uc}=use(fake,false);await expect(uc.create({orderId:o.id,driverId,expectedVersion:o.version,deliveryCode:await code(o.id),readerFamily:'simulated_bluetooth',correlationId:randomUUID()})).rejects.toMatchObject({code:'SimulatedReaderNotAllowed'});fake.accountStatus.cardPayments='pending';const {uc:active}=use(fake,true);await expect(start(active,o)).rejects.toMatchObject({code:'CardPaymentsNotReady'});expect(fake.calls.createTerminalPaymentIntent).toBe(0);await expect(active.get({orderId:o.id,driverId:otherDriverId})).rejects.toMatchObject({code:'OrderNotFoundError'})})
  it('resume does not create second PI; GET hides secret after authorization; token uses snapshot',async()=>{const o=await order();const {uc,fake}=use();const s=await start(uc,o);await start(uc,o);expect(fake.calls.createTerminalPaymentIntent).toBe(1);expect(await uc.connectionToken({orderId:o.id,driverId})).toEqual({secret:'pst_acct_test_tml_acct_test'});expect(await uc.get({orderId:o.id,driverId})).toMatchObject({nextAction:'collect_payment',payment:{paymentIntentClientSecret:'pi_1_secret'}});fake.authorize('pi_1');expect(await uc.get({orderId:o.id,driverId})).toMatchObject({nextAction:'finalize',payment:{paymentIntentClientSecret:null}})})
})
