import { randomUUID } from 'node:crypto'
import { afterEach, describe, expect, it } from 'vitest'
import { pool } from '../../src/platform/db.js'
import { CashOnDeliveryTransitionConflictError } from '../../src/modules/cash-on-delivery/domain/errors.js'
import { PostgresCashOnDeliveryPaymentRepository, PostgresCompletionSessionRepository, PostgresMerchantConnectRepository, PostgresMerchantTerminalLocationRepository } from '../../src/modules/cash-on-delivery/infrastructure/postgres-cash-on-delivery-repositories.js'
import { deleteTestOrders } from '../support/cleanup-orders.js'

const merchantId = '22222222-2222-2222-2222-222222222222'; const driverId = '33333333-3333-3333-3333-333333333333'; const zoneId = '11111111-1111-1111-1111-111111111111'; const orderIds: string[] = []
const sessions = new PostgresCompletionSessionRepository(pool); const payments = new PostgresCashOnDeliveryPaymentRepository(pool); const locations = new PostgresMerchantTerminalLocationRepository(pool); const connect = new PostgresMerchantConnectRepository(pool)
async function order(): Promise<string> { const id=randomUUID(); await pool.query(`insert into orders(id,merchant_id,driver_id,zone_id,status,customer_name,customer_phone,pickup_address,pickup_lat,pickup_lng,delivery_address,delivery_lat,delivery_lng,distance_m,duration_s,driver_earning_cents,cash_on_delivery_required,cash_on_delivery_amount_cents,cash_on_delivery_currency,cash_on_delivery_created_at) values($1,$2,$3,$4,'COLLECTED','Client','0600000000','Pickup',46.2,5.2,'Delivery',46.21,5.23,0,0,400,true,5000,'eur',now())`,[id,merchantId,driverId,zoneId]); orderIds.push(id); return id }
async function attempt(orderId:string,sessionId:string,id=randomUUID()){return payments.createAttempt({id,orderId,sessionId,merchantId,driverId,stripeAccountId:'acct_test',amountCents:5000,currency:'eur',status:'created',captureIdempotencyKey:`capture-${id}`,createIdempotencyKey:`create-${id}`,readerType:'bluetooth',readerSerial:null,terminalLocationId:'tml_test'})}
afterEach(async()=>{await deleteTestOrders(pool,orderIds.splice(0));await pool.query('delete from merchant_terminal_locations where merchant_id=$1',[merchantId]);await pool.query('delete from merchant_stripe_connect where merchant_id=$1',[merchantId])})

describe('Postgres COD repositories',()=>{
  it('resumes same session and keeps one active session under concurrency',async()=>{const id=await order();const input={orderId:id,driverId,expectedOrderVersion:1,expiresAt:new Date(Date.now()+3600000)};const first=await sessions.createOrResume(input);expect((await sessions.createOrResume(input)).id).toBe(first.id);const all=await Promise.all(Array.from({length:5},()=>sessions.createOrResume(input)));expect(new Set(all.map(x=>x.id))).toEqual(new Set([first.id]));const count=await pool.query('select count(*) from order_delivery_completion_sessions where order_id=$1',[id]);expect(Number(count.rows[0]!.count)).toBe(1)})
  it('uses conditional session transition and leaves conflict row unchanged',async()=>{const id=await order();const value=await sessions.createOrResume({orderId:id,driverId,expectedOrderVersion:1,expiresAt:new Date(Date.now()+3600000)});expect((await sessions.transition({id:value.id,from:['open'],to:'code_verified'})).status).toBe('code_verified');await expect(sessions.transition({id:value.id,from:['open'],to:'payment_pending'})).rejects.toBeInstanceOf(CashOnDeliveryTransitionConflictError);expect((await sessions.findByOrderId(id))!.status).toBe('code_verified')})
  it('numbers attempts, finds PI and allows only one active concurrent attempt',async()=>{const id=await order();const s=await sessions.createOrResume({orderId:id,driverId,expectedOrderVersion:1,expiresAt:new Date(Date.now()+3600000)});const one=await attempt(id,s.id);await payments.transition({id:one.id,from:['created'],to:'failed'});const two=await attempt(id,s.id);expect(two.attemptNo).toBe(2);const withPi=await payments.transition({id:two.id,from:['created'],to:'intent_created',stripePaymentIntentId:'pi_repository'});expect((await payments.findByPaymentIntentId('pi_repository'))?.id).toBe(withPi.id);const concurrentOrder=await order();const concurrentSession=await sessions.createOrResume({orderId:concurrentOrder,driverId,expectedOrderVersion:1,expiresAt:new Date(Date.now()+3600000)});const results=await Promise.allSettled(Array.from({length:5},()=>attempt(concurrentOrder,concurrentSession.id)));expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);const count=await pool.query("select count(*) from order_cash_on_delivery_payments where order_id=$1 and status in ('created','intent_created','processing','authorized','unknown')",[concurrentOrder]);expect(Number(count.rows[0]!.count)).toBe(1)})
  it('upserts terminal location and Connect cache',async()=>{await locations.save({merchantId,stripeAccountId:'acct_a',terminalLocationId:'tml_a'});await locations.save({merchantId,stripeAccountId:'acct_b',terminalLocationId:'tml_b'});expect(await locations.findByMerchantId(merchantId)).toMatchObject({stripeAccountId:'acct_b',terminalLocationId:'tml_b'});await connect.save({merchantId,merchantConfiguredAt:null,cardPaymentsStatus:'pending',cartesBancairesStatus:'restricted',requirementsCount:2,lastSyncedAt:null});await connect.save({merchantId,merchantConfiguredAt:new Date(),cardPaymentsStatus:'active',cartesBancairesStatus:'active',requirementsCount:0,lastSyncedAt:new Date()});expect(await connect.findByMerchantId(merchantId)).toMatchObject({cardPaymentsStatus:'active',cartesBancairesStatus:'active',requirementsCount:0})})
})
